### ISSUE TITLE
extrude next/last silently ignores both

### ISSUE THREAD

**Issue by fpq473** [gumyr/build123d#11]
Possibly a bug or a potential enhancement: when extruding to NEXT and LAST, the `both=` parameter is silently ignored.

https://github.com/gumyr/build123d/blob/56b2c954bc442279b969415a480a3d790e307460/src/build123d/build_part.py#L428

**Comment by gumyr** [comment]
This works as of commit 16ee9405994e3d3966a2c603bb8c95d2af77efef

```py
with BuildPart() as ex28:
    Torus(50, 10, rotation=(0, 90, 0))
    with BuildSketch():
        Rectangle(rad, rev)
    extrusion28 = Extrude(until=Until.NEXT, both=True)
```
![image](https://user-images.githubusercontent.com/85638518/210855824-491b5b8a-af05-44f1-b732-fb78058de41c.png)
