### ISSUE TITLE
a typo?

### ISSUE THREAD

**Issue by cyberhuman** [gumyr/build123d#117]
https://build123d.readthedocs.io/en/latest/key_concepts.html#workplane-contexts
In the example it's `Plane.XY` but in the text below it's `XZ`.
![image](https://user-images.githubusercontent.com/979624/216768069-183ff7dc-5005-46c2-b9a2-1cc53275f515.png)

**Comment by gumyr** [comment]
Fixed.  Thanks for pointing the error out.
