### ISSUE TITLE
2D Thicken

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#127]
Thicken an Edge/Wire into a Face.

**Comment by Jojain** [comment]
Isn't what `Offset` is supposed to do?

**Comment by gumyr** [comment]
Offset of a Edge/Wire creates an Wire which goes all the way around the original Edge/Wire. I'm thinking this could be implemented with an Edge.sweep() method which creates a Face from an Edge and a path.

**Comment by Jojain** [comment]
My question is in a BuildSketch context shouldn't offset create a face ? 
I draw a line offset makes a wire and in the sketch context it makes a face out of it

**Comment by gumyr** [comment]
Complete with c858b10e8b31573b377210043b38de2dbb229090  The direct api sweep and the sweep operator can create a Face from a swept Edge.
