### ISSUE TITLE
Idea: Operation mode context

### ISSUE THREAD

**Issue by hiaselhans** [gumyr/build123d#135]
given the following example (from examples/multiple_workplanes.py):

``` python
from build123d import *

with BuildPart() as obj:
    Box(5, 5, 1)
    with Workplanes(*obj.faces().filter_by(Axis.Z)):
        Sphere(1.8, mode=Mode.SUBTRACT)
```

What if we took the context-manager approach one step further and were enabling something like this:

``` python
from build123d import *

with BuildPart() as obj:
    Box(5, 5, 1)

    with obj.SUBSTRACT():
        with Workplanes(*obj.faces().filter_by(Axis.Z)):
            Sphere(1.8)
```

**Comment by Jojain** [comment]
What does this bring ?

The build123d context managers while being powerful are nonetheless a bit complex so I would not be in favor of adding more context managers to allow different ways of doing the same thing.

There is already so much way one can build a part, the more restrictive the API is the easiest it will be to debug.

**Comment by jdegenstein** [comment]
This is not really adding anything new from an end user perspective. Consider the following re-write of the 2nd example using already existing methods:
```py
with BuildPart() as obj_sub:
    with Workplanes(*obj.faces().filter_by(Axis.Z)):
        Sphere(1.8)

with BuildPart() as obj:
    Box(5, 5, 1)
    Add(obj_sub.part,mode=Mode.SUBTRACT)
```

**Comment by hiaselhans** [comment]
thanks @jdegenstein that seems decent enough for me.

Here is the same thing with nested BuildParts (in order to have obj.faces available):

``` python
with BuildPart() as obj:
    Box(5, 5, 1)

    with BuildPart() as obj_sub:
        with Workplanes(*obj.faces().filter_by(Axis.Z)):
            Sphere(1.8)

    Add(obj_sub.part,mode=Mode.SUBTRACT)
```

**Comment by jdegenstein** [comment]
Good point, here is another tweak: `with BuildPart() as obj_sub:` should be `with BuildPart(mode=Mode.PRIVATE) as obj_sub:`  as it prevents from adding to the parent
