### ISSUE TITLE
Should b3d operations be functions instead of classes

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#183]
Currently both objects and operations are built from classes. Methods weren't used for operations as that impacts expandability unless one monkey-patches classes which has many negative side effects.  However, plain functions don't have this problem and would be just as versatile as classes from an expandability point of view.

Nothing else need change from a user's point of view other then the use of lower-case.  For example:
```py
length, width, thickness = 80.0, 60.0, 10.0

with BuildPart() as ex3:
    with BuildSketch() as ex3_sk:
        Circle(width)
        Rectangle(length / 2, width / 2, mode=Mode.SUBTRACT)
    Extrude(amount=2 * thickness)
```
would become:
```py
length, width, thickness = 80.0, 60.0, 10.0

with BuildPart() as ex3:
    with BuildSketch() as ex3_sk:
        Circle(width)
        Rectangle(length / 2, width / 2, mode=Mode.SUBTRACT)
    extrude(amount=2 * thickness)
```

Clearly this is not a backwards compatible change but one that wouldn't be too hard to implement.

What does the community think?

**Comment by Jojain** [comment]
Can we first define clearly what is an object and what is an operation?

**Comment by bernhard-42** [comment]
For Parts some ideas for discussion

```text
Objects
- Box(BasePartObject)
- Cone(BasePartObject)
- Cylinder(BasePartObject)
- Sphere(BasePartObject)
- Torus(BasePartObject)
- Wedge(BasePartObject)

"Anti matter" objects (use add to remove something)
- Hole(BasePartObject)
- CounterBoreHole(BasePartObject) 
- CounterSinkHole(BasePartObject)

Operations
- Extrude(Compound) => extrude
- Revolve(Compound) => revolve
- Sweep(Compound) => sweep
- Section(Compound) => section
- Loft(Solid) => loft ?
- class Chamfer(Compound) => chamfer
- Fillet(Compound) => fillet
- Mirror(Compound) => mirror
- Offset(Compound) => offset
- Scale(Compound) => scale
- Split(Compound) => split
```

**Comment by Jojain** [comment]
From there I can understand what we would define as object or operation but having a clear definition would help to classify things when they will come in the future. (And it also helps clarify the concepts for everyone)

**Comment by bernhard-42** [comment]
An attempt:
- An `Object` is derived from `BasePartObject` and is an OCCT Shape (i.e. can be described as a tuple `(topology, location)`)
- An operation takes one or more `Object`s (see above) and creates one or more other `Object`s.

One view at the API layers could be:
- `direct API => algebra API => context API`
- `methods    => functions   => classes`

**Comment by Jojain** [comment]
So we could say that an operation modifies one or several objects. And an object class creates a totally new one right ?

**Comment by snoyer** [comment]
> Methods weren't used for operations as that impacts expandability unless one monkey-patches classes which has many negative side effects. However, plain functions don't have this problem and would be just as versatile as classes from an expandability point of view.

Can you expand on that point? What are the pros and cons of each approach within b3d?

Given that the Builder API does not follow the conventional object-oriented paradigm the distinction between classes, functions, and methods is not relevant to user code (at least not in the given example). The choice can then be based on what make the backend better/easier

> Nothing else need change from a user's point of view other then the use of lower-case. For example:

Even this one is up to you to decide.
Python's own `map`, `filter`, `zip` used to be functions before `3.x`, now they're classes without having changed names. They are still used and can be reasoned about as though they are functions (you don't expect to do `y = map(f, z)` and then `y.foo()` like you would on a object) but from an implementation point of view (to make the mapping, filtering, zipping operations lazy) it makes sense for them to be classes.

edit to be clearer: I believe there are 2 orthogonal questions here:
1. should b3d, from a user point of view, distinguish between objects and operation? and if so does using use lower case names for operations make sense?
2. should operations be implemented as functions? and maybe the answer here is along the line of "preferably, unless class makes more sense"

**Comment by bernhard-42** [comment]
> So we could say that an operation modifies one or several objects. And an object class creates a totally new one right ?

Yep, that's my mental model for it.

> I believe there are 2 orthogonal questions here:

I like your distinction of the two topics: 
- I would say yes to 1 (it kind of feels more pythonic to me)
- And I agree with your pragmatic approach in 2. For the type of operations we have, not sure we need methods for them or subclass them. But that's for discussion

**Comment by gumyr** [comment]
All operations are now functions.
