### ISSUE TITLE
Taper fails on example 3 from the docs

### ISSUE THREAD

**Issue by mggevaer** [gumyr/build123d#184]
Taper fails for following example:
```Python
with BuildPart() as ex:
    with BuildSketch() as ex_sk:
        Circle(width)
        Rectangle(length/2, width/2, mode=Mode.SUBTRACT)
    Extrude(amount=2*thickness, taper=45)
```
with error: `OCP.StdFail.StdFail_NotDone: BRepFill_TrimSurfaceTool::IntersectWith: incoherent intersection`

It also fails for:
```Python
with BuildPart() as ex:
    with BuildSketch() as ex_sk:
        Circle(width)
        Rectangle(length/2, width/2, mode=Mode.SUBTRACT)
    Extrude(amount=2*thickness, taper=-45)
```
but in a different way, it doesn't include the rectangle cutout.
![image](https://user-images.githubusercontent.com/41551215/225777475-f12c4d60-10e1-4f52-9fb9-2845f4002407.png)

Works fine without taper:
![image](https://user-images.githubusercontent.com/41551215/225777511-fc4ceca7-e9e0-4cb6-a939-54c610c41cfb.png)

**Comment by gumyr** [comment]
I've changed extrude such that when there is a taper, extrude the face without holes, extrude the holes and cut the extruded holes from the extruded face.  This results in:
![image](https://user-images.githubusercontent.com/85638518/231545251-5d67803d-4bbd-4205-aae8-c91595255661.png)
