### ISSUE TITLE
Face not coplanar with Sketch

### ISSUE THREAD

**Issue by jdegenstein** [gumyr/build123d#187]
```py
from build123d import *

with BuildPart() as p:
    Box(10,10,10)
    
with BuildSketch(p.part.faces().sort_by(Axis.Z)[-1]) as s:
    Offset(p.part.faces().sort_by(Axis.Z)[-1],amount=-1)
```
gives the error `ValueError: Face not coplanar with sketch` in relation to the call to Offset()

**Comment by gumyr** [comment]
Commit 3d6414d06b01970771ff695ea55cc74e14778175 realigns all faces add to a Sketch to its local Plane.XY which allows faces to be added without the `coplanar` error.  Here is a slightly move difficult version of the above:

```py
with BuildPart() as p:
    Box(10, 10, 10)
    front = p.part.faces().sort_by(Axis.X)[-1]
    with BuildSketch(front) as s:
        offset(front, amount=-1)
    extrude(amount=-1, mode=Mode.SUBTRACT)
```
![image](https://user-images.githubusercontent.com/85638518/230734664-4f7b6fd5-f9ff-47ec-bc78-4ceace5f7d67.png)

It's still possible to get into trouble by adding non co-planar edges as determining the plane they come from is problematic. Note that if the edges are built in BuildLine all the translation is done for the user automatically.

**Comment by jdegenstein** [comment]
Thanks gumyr!
