### ISSUE TITLE
Plane() initializer sometimes ignores arguments

### ISSUE THREAD

**Issue by barnabywalters** [gumyr/build123d#188]
In cases where named and positional arguments are mixed, like this (and probably many others, but this is the real-world example I ran into):

```python
Plane((0, 0, 0), x_dir=(1, 0, 0), z_dir=(0, 0, 1))
```

the first argument is ignored by `__init__`, as it expects either all positional or all named arguments. IMO b3d should either attempt to handle mixed arguments somehow (e.g. in this case inferring that it’s the origin), or at least raise an error when it ignores an argument, so that the user is aware of what’s happening. Something like:

```python
if args and kwargs:
  raise ValueError("Plane() initializer expects either positional OR named arguments, not both")
```

**Comment by gumyr** [comment]
I've lot track of the commit that fixed this but:
```py
from build123d import *

p = Plane((1, 1, 1), x_dir=(1, 0, 0), z_dir=(0, 0, 1))
print(p)
```
```
Plane(o=(1.00, 1.00, 1.00), x=(1.00, 0.00, 0.00), z=(0.00, 0.00, 1.00))
```
shows that it's fixed now.
