### ISSUE TITLE
Add Tips/Best Practises page to the documentation

### ISSUE THREAD

**Issue by barnabywalters** [gumyr/build123d#189]
Could be useful to have a page in the documentation where we collect tips, solutions to common issues and best practices to guide people not familiar with OCCT’s internals. Some examples from the discord chat:

On cutting out shapes by modeling the void and subtracting it vs. sketching and doing negative extrusions:
> Usually we promote 2d sketch and then extrude/hole to go 3D
> In general, the CSG style of building that's common with folks who are coming from OpenSCAD (which included me) is somewhat problematic. Complex boolean operations are slow and have a high potential to fail. 
(jojain + Roger Maitland)

On when to fillet/chamfer:

> I also recommend you do your fillets on the lowest level geometry possible (more stable and less likely to get crashes), so in this case I think you could do some of the fillets on the 2D sketch s. It is also recommended to do the fillets on 3D geometry towards the end, if possible.
(Jern)

Potentially paraphrased to “when possible, fillet/chamfer early in 2D or late in 3D, to reduce the number of complex boolean operations required”

**Comment by barnabywalters** [comment]
On how to select edges in a complex part:

> start to select the face first and then select the edges from the faces
> (jojain)

to which I would add: keep references to various solids, planes and faces around as you construct your objects, so they’re easily available later on when making selections. It’s usually easier to make selections early rather than late

**Comment by gumyr** [comment]
With this commit (edd4ae8f6e7103716f5e07733193990e13af7628) I'll consider this particular issue closed. However, more tips are always welcome.
