### ISSUE TITLE
Contextual help via LSP

### ISSUE THREAD

**Issue by smallstepman** [gumyr/build123d#19]
In cq v2 one can develop things using "dot-tab workflow", e.g. 
```python
x = cq.Workplane().box(1,2,3)
x. <PRESS TAB to open LSP hints>
```

Do you think such workflow would be possible with build123d?

**Comment by gumyr** [comment]
Improving support for IDEs was one of the design goals. To facilitate expansion build123d is class based not method based so this works a little differently.

This is what I see with Visual Studio Code:
![image](https://user-images.githubusercontent.com/85638518/192377633-18370257-d817-4633-abd6-da1187731798.png)
Are you looking for more than this?  It would be nice to be able to shorten this list to just the build123d specific classes - possibly even the ones that would apply in that context.

Enums are used throughout for similar reasons:
![image](https://user-images.githubusercontent.com/85638518/192378485-ca3a3091-fea3-4459-a65b-f20d0a03fb79.png)
one can clearly see what the options are and quickly select one of them.

I don't know much about LSP, is there a language specification that could be created to improve usability?

**Comment by smallstepman** [comment]
I'm no expert either, but I believe there is a way to sort entries in the suggestion list, however, I tried to search for it but could not find anything

**Comment by gumyr** [comment]
Don't know of anything else that can be done at this point to further enhance contextual help.
