### ISSUE TITLE
Error with 360 degree JernArc

### ISSUE THREAD

**Issue by jdegenstein** [gumyr/build123d#192]
The following should draw a circle, but throws an error:
```py
from build123d import *
rad = 5

with BuildLine() as l:
    l1 = JernArc(start=(0,0,0),tangent=(1,0,0),radius=rad,arc_size=360)

show_object(l.line)
```
`Standard_ConstructionError: gp_Dir::Crossed() - result vector has zero norm`

This works fine for e.g. 359 degrees

**Comment by gumyr** [comment]
Enhanced to allow the creation of a complete circle.
