### ISSUE TITLE
Improve Centering

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#20]
Centering should be based on the U (UV) center of Edge/Wires, Faces not on center of mass.  Potentially use ShapeAnalysis_Surface.Value() to find the UV center.

**Comment by Jojain** [comment]
Maybe this could be an option. I think people will expect one or the other given the context, since there is no way to know what they expect in the code, providing the option to chose seems interesting ?

**Comment by gumyr** [comment]
Where appropriate, the `center` methods contain a `center_of` parameter:
```py
    def center(self, center_of: CenterOf = CenterOf.GEOMETRY) -> Vector:
```
where:
```py
class CenterOf(Enum):
    """Center Options"""

    GEOMETRY = auto()
    MASS = auto()
    BOUNDING_BOX = auto()
```
