### ISSUE TITLE
Segfault when splitting filleted objects

### ISSUE THREAD

**Issue by barnabywalters** [gumyr/build123d#209]
Under certain circumstances, calling `split()` on a part will cause a segfault. This seems especially likely to happen if the part contains fillets, and is bisected along a plane with an offset or a funny angle (presumably when the plane is intersecting with features derived from the fillets?)

```python
with BuildPart() as p:
    with BuildSketch() as s:
        with BuildLine() as l:
            Polyline(
                (0, 0),
                (0, 10),
                (10, 20),
                (10, 0),
                (0, 0)
            )
        make_face()
        fillet(s.vertices(), radius=1)  # adding this line causes the segfault
    revolve(axis=Axis.X)
    
    split(bisect_by=Plane((5, 5, 0)), keep=Keep.BOTTOM)  # Works
    split(bisect_by=Plane((5, 5, 0), z_dir=(1, 1, 2))) # segfault
    split(bisect_by=Plane((5, 5, 1)), keep=Keep.BOTTOM)  # segfault
show(p)
```

A more complex example can be found [here](https://gist.github.com/barnabywalters/5e39320a66bcd5ae389facb952c010b6) (and is the basis for the next example)

Manually making a cutter and inverting the plane resulted in the correct bisection, without a segfault:

```python
cutter = (-shoe_duct_plane).from_local_coords(
    Solid.make_box(120, 120, 120).moved(Location((-60, -60, 0)))
)
segfault = dust_shoe.part.intersect(cutter)
```
![](https://media.discordapp.net/attachments/1074840524181217452/1094623246432878642/image.png?width=1206&height=930)

But according to Roger:

> I modified split to invert the plane instead of moving the cutter and it still segfaults.  Truly strange.

It’s not currently clear exactly what is causing this or how to fix it.

**Comment by gumyr** [comment]
Works with the new split algorithm - see commit 702296f
![image](https://github.com/gumyr/build123d/assets/85638518/dceba4af-d109-485f-8b04-b57941aaa684)
