### ISSUE TITLE
Strange behavior of CenterArc with offset

### ISSUE THREAD

**Issue by OvisMaximus** [gumyr/build123d#214]
Given the following code
```py
from build123d import *

ring_diameter = 110

with BuildPart(Plane.XZ) as part_builder:
    with BuildLine(Plane.XY) as sweep_path:
        a_clamp_width = 12
        CenterArc((-ring_diameter/2, 0), ring_diameter / 2, -a_clamp_width / 2, a_clamp_width)

    with BuildSketch(Plane.XZ) as sketch_builder:
        Rectangle(4.0, 8.0, align=(Align.CENTER,Align.MIN))

    sweep()
    #extrude(amount=5, both=True)

show_object(part_builder.part.wrapped, name="part")
show_object(sweep_path.line.wrapped, name="sweep_path")
show_object(sketch_builder.sketch.wrapped, name="sketch")
```

The sweep-path is a circle segment on the XY plane crossing the (0, 0, 0) coordinate. This is what we got rendered:
![image](https://user-images.githubusercontent.com/5701377/231964926-317eea44-eb14-4d01-94de-ffbb90d2027c.png)

when we move the CenterArc to (0,0) in its initializer, we will get:
![image](https://user-images.githubusercontent.com/5701377/231967123-82a54a7f-714c-468f-8170-1de1b789250f.png)
the latter meets my expectation, the first doesnt.

**Comment by gumyr** [comment]
There indeed was a bug which has been fixed - thanks for reporting it.  The path is now:
![image](https://user-images.githubusercontent.com/85638518/232329110-b79a803e-7546-49b9-8088-6f920fa888c4.png)
