### ISSUE TITLE
BuildSketch seems to ignore a surrounding Locations context

### ISSUE THREAD

**Issue by bernhard-42** [gumyr/build123d#221]
See https://discord.com/channels/964330484911972403/1074840524181217452/1099589193451188284 

Simple example to reproduce:

```python
with BuildSketch() as c:
    Circle(1)

with Locations(Pos(2,0)):
    with BuildSketch() as r:
        Rectangle(1,1)

show(c, r, names=["c", "r"])

# %%

with BuildSketch(Pos(2,0)) as r2:
    Rectangle(1,1)

show(c, r2, names=["c", "r2"])
```
<img width="479" alt="image" src="https://user-images.githubusercontent.com/954408/233825039-f851d1ca-c943-41ec-af8a-499575e9a965.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/954408/233825055-07291f64-8bc7-403f-aed3-18068f50fbcf.png">

**Comment by gumyr** [comment]
Thanks for pointing this out. There was a simplification made so this rule applies now: It’s important to note that objects created by operations are not affected by Locations, meaning their position is determined solely by the input objects used in the operation. (from https://build123d.readthedocs.io/en/latest/operations.html#operations)  so the logo should be changes as you described.
