### ISSUE TITLE
CenterArc fails to draw clockwise

### ISSUE THREAD

**Issue by OvisMaximus** [gumyr/build123d#222]
given this code:
```
from build123d import *

with BuildPart(Plane.XZ) as clamp:

    with BuildSketch(Plane.XZ) as sketch_builder:
        with BuildLine(Plane.XZ) as shape:
            t0 = CenterArc((0, 0), 4, 0, 40)
            t1 = CenterArc((0, 10), 4, 0, -40)

        make_face()

show_object(t0.wrapped, name="segment a_start=0 dir=pos")
show_object(t1.wrapped, name="segment a_start=0 dir=neg")
```

I expect two segments of a circle painted on the XZ plane. 
The arc at the coordinate root starting on the X axis counter clockwise 40°.
The arc 10 units above the coordinate root starting 10 units above the X axis clockwise 40°.

The first segment is rendered as expected, the second starts as expected at the expected position, but instead of "40° clockwise " "320° counter clockwise" are rendered.

**Comment by gumyr** [comment]
Thanks.  The problem was in the direct api `make_circle` method and is now fixed:
![image](https://github.com/gumyr/build123d/assets/85638518/9b2e54fc-1f8e-4b5d-b55f-f289a6107abb)
