### ISSUE TITLE
3MF export leaves open edges

### ISSUE THREAD

**Issue by JonnyHaystack** [gumyr/build123d#232]
After exporting a model as 3MF like so,
```py
rpi_mount.plate.export_3mf(
    "4Max_Pro_RPi_Touchscreen_Mount_Plate.3mf",
    tolerance=1e-3,
    angular_tolerance=0.1,
    unit=Unit.MILLIMETER,
)
```

I opened this file in PrusaSlicer and noticed it had a warning about the model having 9720 open edges, and 50 shells when it should have 1:
![image](https://user-images.githubusercontent.com/1266473/235526570-8f1f6870-a126-4818-87e1-3c721a15f198.png)

When exporting the exact same model as STL, this warning is not present, and I see 1 shell as I would expect:
![image](https://user-images.githubusercontent.com/1266473/235526811-ae086237-fed0-42e8-946e-baa8a1d6c9a0.png)

**Comment by gumyr** [comment]
The 3MF exporter has be totally rewritten to use the 3MF Consortium's Lib3MF which doesn't allow non manifold meshes. See: https://build123d.readthedocs.io/en/latest/import_export.html#d-mesh-export
