### ISSUE TITLE
export_3mf() has no default values for its parameters

### ISSUE THREAD

**Issue by JonnyHaystack** [gumyr/build123d#233]
`export_stl()` has default values for its `tolerance` and `angular_tolerance` parameters, however `export_3mf()` does not have any default parameter values. Unless there is a particular reason for this, I think it would make sense to have reasonable defaults for all of the export functions.

**Comment by gumyr** [comment]
3MF Exporter has changed, see: https://build123d.readthedocs.io/en/latest/import_export.html#d-mesh-export with appropriate defaults.
