### ISSUE TITLE
Plane.to_local_coords(vertex) doesn't seem to work

### ISSUE THREAD

**Issue by JonnyHaystack** [gumyr/build123d#236]
`Plane.to_local_coords()` doesn't seem to do anything when you pass a Vertex into it, but if you convert that same Vertex to a vector with `Vertex.to_vector()`, it works as one would expect.

```
vertex: Vertex: (-14.5, 9.999999999999996, 25.0)
vertex.to_vector(): Vector: (-14.5, 9.999999999999996, 25.0)
plane.to_local_coords(vertex): Vertex: (-14.5, 9.999999999999996, 25.0)
plane.to_local_coords(vertex.to_vector()): Vector: (9.999999999999996, 11.666666666666664, 0.0)
```

**Comment by gumyr** [comment]
This problem illustrates a bit of weirdness of the OCP core - vertices within objects can be transformed but not raw.  Added a special case to handle this.  

Now:
```py
plane = Plane.YZ
vertex = Vertex(-14.5, 10, 25.0)
print(plane.to_local_coords(vertex))
print(plane.to_local_coords(vertex.to_vector()))
```
results in:
```
Vertex: (10.0, 25.0, -14.5)
Vector: (10.0, 25.0, -14.5)
```
