### ISSUE TITLE
Plane.set_origin2d method does not issue a return object and is not in sync with documentation 

### ISSUE THREAD

**Issue by WhichQuord** [gumyr/build123d#263]
Plane.set_origin2d method does not return a Plane object, thus code like the following raises an Error: 
 `with BuildSketch(Plane.XY.set_origin2d(10,10)):`

Plane.set_origin2d method implementation is absolute rather than relative, in contrast with the comments/documentation.

**Comment by gumyr** [comment]
`Plane.set_origin2d` has been refactored to take either an Axis or Vertex to set the origin and returns a new Plane object.  See 8125af82aad66bf2c279717d0996e3e46ebd8559
