### ISSUE TITLE
Add new Curve Object - FilletPolyline

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#265]
Create a version of Polyline that has radius parameter which will fillet all the internal (i.e. not end) vertices. The plane to implement the fillet is calculated for each vertex from the adjoining Edges such that it works for 3D paths.  An example of the code could be:
```py
with BuildPart() as pipe_example:
    with BuildLine(Plane.YZ) as pipe_path:
        FilletPolyline((0, 0), (10, 0), (10, 10), (20, 10), radius=1)
        scale(by=FT)
    Pipe(nps="10", material="stainless", identifier="10S")
```
![image](https://github.com/gumyr/build123d/assets/85638518/aecaec0e-19a6-4da5-8ebd-180ef7607d4e)

**Comment by jdegenstein** [comment]
This sounds very useful!

**Comment by gumyr** [comment]
Complete with commit 489fcb02f9dfe7c548e702df381301fc5393fbb6

**Comment by gumyr** [comment]
Works for closed objects as well:
![image](https://github.com/gumyr/build123d/assets/85638518/5a79efc9-74df-4103-8f3e-855079d17e28)
