### ISSUE TITLE
Attempting to use zero as a value for Color red/green/blue results in one instead

### ISSUE THREAD

**Issue by voneiden** [gumyr/build123d#272]
Doing something like

```python
color = Color(red=0, green=0, blue=0)
```
will actually result in a `Color(1, 1, 1)` due to the way the code checks kwargs:

https://github.com/gumyr/build123d/blob/dev/src/build123d/geometry.py#L807

0 will cause the if to be skipped so the default of 1 is used instead.

Will submit a PR to address this shortly.

**Comment by gumyr** [comment]
Closed with cdfeb7e3b65cb679a9c31920105ced25c127350d

Thanks
