### ISSUE TITLE
svg import from solvespace not working as expected

### ISSUE THREAD

**Issue by bernhard-42** [gumyr/build123d#300]
I was playing around with SolveSpace and created this sketch:
<img width="540" alt="image" src="https://github.com/gumyr/build123d/assets/954408/e69de8d9-519b-4907-88f2-95ac74e83d29">

Affinity Designer imports it as 
<img width="566" alt="image" src="https://github.com/gumyr/build123d/assets/954408/4fe0c8bf-7c9c-455c-b05e-ee37993b361e">

However, importing into build123d with

```python
p = import_svg("profile.svg")
show(p)
```

results in 

<img width="407" alt="image" src="https://github.com/gumyr/build123d/assets/954408/e53f5fac-5c4d-4d3c-a410-f8301e4a5220">

Two issues:
1) the whole sketch is flipped vertically
2) one of the arcs goes in the wrong direction

The SolveSpace file and the svg can be found on Discord (https://discord.com/channels/964330484911972403/1074840524181217452/1141086336124719165)

**Comment by gumyr** [comment]
With commit dd4f923f6cd62d25c45dc4188bf223778047e619 both problems are fixed - the arc is correct and there is a parameter to flip y which defaults to True.
![image](https://github.com/gumyr/build123d/assets/85638518/2de4c3ab-053e-4f20-ae85-09f7c9e5cf60)
