### ISSUE TITLE
Add a major/minor radius flag parameter to the Polygon shapes

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#312]
Currently the radius provided is the major radius (that of the circumscribed circle) - the new flag would indicate that the radius is a minor radius (that of the inscribed circle) thus allowing either of the hexes shown in this example to be created without the user doing any mathematics.

![image](https://github.com/gumyr/build123d/assets/85638518/15024413-1220-4498-a944-5b48944b7c98)

**Comment by jdegenstein** [comment]
The ratio of the inscribed radius r to the circumscribed radius R is `r/R = cos(pi/n)` where n is the number of sides of the regular polygon. For instance `r/R = 0.866...` for a hexagon and `r/R = 0.5` for a triangle.

**Comment by gumyr** [comment]
Thanks @jdegenstein !
