### ISSUE TITLE
Change Shape.geom_type() to use GeomType values

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#321]
`GeomType` should be changed to a `StrEnum` and use the same values as generated by `Shape.geom_type()` so that `edge.geom_type() == GeomType.CIRCLE` works.

Should `Shape.geom_type` be a property instead of a method?

**Comment by Jojain** [comment]
Isn't it possible to make geom_type return the enum directly? But otherwise making it a str enum would be better !
+1 for the property
