### ISSUE TITLE
Intersections on planes and axis

### ISSUE THREAD

**Issue by Jojain** [gumyr/build123d#327]
It would be nice to have more features on the "geometry" objects and not rely only on the topo object.
Nice improvement would be :
- Intersections of plane between plane, returns an axis, which start point could be the projected mid point of the origin of the two plane onto the axis
- Intersections of axis with axis, it would return a point. The axis would need to be in the same plane or if not maybe the intersection can be return in the mid plane of both axis.
- It can be nice to have a function to compute a mid axis given two axis.

**Comment by gumyr** [comment]
@Jojain I'm trying to complete this feature now - I need more info on the 3rd point.  Would this case only apply to two Axes that are parallel?

**Comment by Jojain** [comment]
No, the axis can be in whatever orientation, 2 axis can always be considered in the same plane, with potentially one of the axis offset in the Z direction of the common plane. In such case the start point of the mid axis is the intersection of the two axis in the common plane projected in the mid plane. And the mid axis direction is the mid vector of the axis direction.

![image](https://github.com/gumyr/build123d/assets/50221409/c7af7f39-ae3c-402a-b7b5-c9675aeef858)

Would yield: 
![image](https://github.com/gumyr/build123d/assets/50221409/5c39a4ab-0e8b-42a1-86ec-2c1f316cd78b)

Top view:
![image](https://github.com/gumyr/build123d/assets/50221409/a6a456ec-18a5-463f-9a30-06d665187155)

Then the case when axis are parallel is a special case where the start point is the mid point of both axis start point as you won't be able to find an intersection

**Comment by gumyr** [comment]
Thanks for the clarification. This mid axis feature seems to be very specialized - when would this feature be used?

**Comment by Jojain** [comment]
I don't think its very specialized, I think it's a basic geometric tool. Basically it does in one function call a mid vector computation as well as a mid point one. If you will it's not needed no need to bother with that though, intersections are the priority !

**Comment by gumyr** [comment]
I've split the mid axis feature out to a separate Issue so I can close this issue.  Now all geometric objects (Vector, Location, Axis, Plane) can intersect each other and at least is some a basic way intersect Shapes.  However, there are many possibilities when doing Shape intersections so I expect new Shape functionality will be required to cover off all of the possibilities.
