### ISSUE TITLE
sweeping along a helix twists the 2d shape

### ISSUE THREAD

**Issue by yshui** [gumyr/build123d#349]
code:

```python
with BuildPart() as screw:
    with BuildLine():
        t = Helix(4, 30, 6.35)
    with BuildSketch(Plane(origin=t @ 0, z_dir = t % 0)):
        Rectangle(2, 2)
    sweep()
```

I expect the square to rotate around the axis of the helix, i.e. perpendicular to the helix. but instead the square also gets twisted around a axis that's tangential to the helix:

![a](https://github.com/gumyr/build123d/assets/366851/1e690026-9c93-4b79-b82f-9b8a67fb8a2e)

**Comment by jdegenstein** [comment]
I believe this is expected behavior, here is how you can "fix" it by adding `is_frenet=True` to `sweep()`

![image](https://github.com/gumyr/build123d/assets/16868537/c4cd3511-ebc6-48b7-a34d-bf4c8f142c5d)

**Comment by yshui** [comment]
Thanks!

Can you explain a bit why it twists, and what frenet is?

**Comment by jdegenstein** [comment]
There is a good writeup on the FreeCAD docs (build123d uses the same OCCT CAD core as FreeCAD, so typically most of the same considerations apply) https://wiki.freecad.org/Part_Sweep#Frenet

**Comment by yshui** [comment]
Thank you!
