### ISSUE TITLE
Trapezoid width inconsistent for obtuse angles

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#380]
`Trapezoid` provides a width, height, and angle parameter. If angle <= 90, the width/height are maintained. If angle >90 the width is no longer consistent.

Optionally could be replaced with min_width and max_width parameter. Could allow specifying either angle + one of max/min width or both max/min width and no angle. That would still leave whether top/bottom are larger so it could be top_width and bottom_width.

<img width="662" alt="ss" src="https://github.com/gumyr/build123d/assets/149267773/ab41fc77-8837-48bf-be7e-62183b057fe9">

**Comment by jdegenstein** [comment]
I believe "width" is referring to "base width" but I agree this is not as clear as it should be.
