### ISSUE TITLE
BuildPart's workplanes do not affect nested BuildSketch

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#398]
```py
with BuildPart(Plane.XZ) as p:
    Cylinder(1, 5)
    with BuildSketch() as s:
        Circle(1)
    extrude(amount=5)
```

<img width="293" alt="s" src="https://github.com/gumyr/build123d/assets/149267773/8e1e6b68-a48a-4236-baf6-20cbf27abdd8">

**Comment by gumyr** [comment]
This is by design. There is no attempt to inherent workplanes from nested objects as there could be many levels of nesting with sub-classing and use within functions which could be very confusing for the user.

**Comment by MatthiasJ1** [comment]
This would contradict that:

```py
with BuildPart() as p:
    with BuildSketch(Plane.XY.shift_origin((3,))) as s:
        with BuildLine():
            CenterArc((0,0), 1, 0, 360)
        make_face()
    extrude(amount=5)
```
<img width="385" alt="Screenshot 2023-12-02 at 12 37 47 PM" src="https://github.com/gumyr/build123d/assets/149267773/50143888-4058-4621-872c-8d38c1503d5b">
