### ISSUE TITLE
Solid.intersect(Axis) fails in trivial example

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#407]
```py
p = Pos(0, 0, 1) * Box(1, 1, 1)
p.solid().intersect(Axis.Z)
```
Results in
```
ValueError: Null TopoDS_Shape object
```

The inverse works but does not appear to be documented (https://build123d.readthedocs.io/en/latest/direct_api_reference.html#geometry.Axis):
```py
p = Pos(0, 0, 1) * Box(1, 1, 1)
Axis.Z.intersect(p.solid())
```

**Comment by jdegenstein** [comment]
I believe the intersect methods are under review at the moment, so they are subject to change. Thank you for reporting though! https://github.com/gumyr/build123d/issues/328
