### ISSUE TITLE
Face.position_at does not always return a valid location on the face

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#408]
```py
s = Rectangle(10,10) - Circle(3)
p = s.face().position_at(0.5,0.5)
```

<img width="239" alt="s" src="https://github.com/gumyr/build123d/assets/149267773/d546ba77-5c92-4b0a-a43c-f3cf3d78ddbf">

**Comment by MatthiasJ1** [comment]
This may be an invalid use case, if so it could just be documented. This came up when testing edge cases for an implementation of `Solid.arbitrary_interior_point`. If this is an acceptable failure for this function, `Solid.arbitrary_interior_point` would also fail for geometries as such:
<img width="257" alt="2" src="https://github.com/gumyr/build123d/assets/149267773/5fc9d7d4-0f42-46ee-9e55-7aa2075bb24d">

**Comment by gumyr** [comment]
One can use `is_inside` to check for holes as follows:
```py
s = Rectangle(10, 10) - Circle(3)
p = s.face().position_at(0.5, 0.5)
print(s.face().is_inside(p))
```
```
False
```
