### ISSUE TITLE
Face.position_at and Face.normal_at have very inconsistent signatures

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#410]
`Face.position_at` takes required normalized u, v coordinates as separate arguments.

`Face.normal_at` takes optional non-normalized (ironically) u, v coordinates as a tuple.

**Comment by jdegenstein** [comment]
related to https://github.com/gumyr/build123d/issues/250

**Comment by gumyr** [comment]
Now `Face.normal_at` takes either a surface point or a u,v value to match the u,v inputs of `Face.position_at`.
