### ISSUE TITLE
BuildPart and BuildLine should have part_local and line_local to be consistent with BuildSketch

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#416]
These should also have an alias `Builder.built` and `Builder.built_local` to provide a consistent api for all 3 for dimensionally agnostic operations.

**Comment by gumyr** [comment]
BuildSketch is a special case as all sketching is done on a local Plane.XY hence the need to have available both the local version and the `sketch` version which contains the sketch(es) positioned in their target location(s). As this behaviour is unique to BuildSketch, the other builders don't have the concept of "local".
