### ISSUE TITLE
Rotation of the first object inside sketch determines the overall orientation of the sketch

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#418]
This breaks the hierarchical nature of the builder contexts and is confusing when the first object does not determine the overall shape like below where it is insignificant.

```py
def make_part(initial_rot):
    with BuildPart() as p:
        with BuildSketch():
            Rectangle(1,1, rotation=initial_rot)
            Rectangle(25,25)
        extrude(amount=10)
        with BuildSketch(*(p.faces()>>Axis.Z)):
            Rectangle(20,20)
        extrude(amount=3)
    return p.part

make_part(0)
make_part(45)
```

![Screenshot 2023-12-02 at 8 39 43 PM](https://github.com/gumyr/build123d/assets/149267773/1bfbc608-a726-4282-99b5-22fc2f52eab4)

**Comment by gumyr** [comment]
The Plane created with `with BuildSketch(*(p.faces()>>Axis.Z)):` does not have an x direction specified so one is determined by OCCT automatically and this is influenced in a non-obvious way by previous geometry.  If the x direction is important to the design, it must be specified.

By the way, `BuildSketch(p.faces()>>Axis.Z)` works now.
