### ISSUE TITLE
Sphere edge tangent incorrect

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#436]
```py
s = Sphere(10)
e = s.edge()
l = Location(e@0.7, e%0.7)
```

![Screenshot](https://github.com/gumyr/build123d/assets/149267773/b9088751-783a-4b24-beac-3adf5863436e)

**Comment by gumyr** [comment]
It looks correct to me:
```py
from build123d import *
from ocp_vscode import *


sphere_edge = Sphere(1.5).edge()
tangent = Line(sphere_edge @ 0.7, (sphere_edge @ 0.7) + (sphere_edge % 0.7) * 1.5)
loc = sphere_edge.location_at(0.7)

show(sphere_edge, tangent, loc)
```
![image](https://github.com/gumyr/build123d/assets/85638518/c5c840ea-5266-4df2-9536-d774a36c2f8d)

**Comment by MatthiasJ1** [comment]
Ah I assumed `Location(A:vector, B:vector)` would construct a Location with `position=A` and `normal=B` but instead it does `position=A` and `normal=euler_angles(B)`. I don't see a constructor for creating a Location with position and normal, what is the recommended method? `Mixin1D.location_at` uses direct OCCT functions. `Location(Plane(sphere_edge@0.7, zdir=sphere_edge.tangent_at(0.7)))` does not work either, but this may be a bug unless I am misinterpreting something again:

```py
p = Plane((0,0,0), xdir=(0,0,1), zdir=(1,0,0))
```

![Screenshot](https://github.com/gumyr/build123d/assets/149267773/fcc31f89-ff37-4891-b1cf-45432dc1af06)

**Comment by gumyr** [comment]
The problem with the Location from Plane is that Plane silently discards invalid kwargs (it's `x_dir` not `xdir`) and should be fixed:
```py
show(Location(Plane((0, 0, 0), x_dir=(0, 0, 1), z_dir=(1, 0, 0))))
```
![image](https://github.com/gumyr/build123d/assets/85638518/42b6204f-f9d0-44fd-bc65-8d2b2b3491b0)

@jdegenstein and I have been discussing changing the `Location.__init__` signatures as we agree they don't seem to represent the common use cases.

**Comment by gumyr** [comment]
I've raised two new issues to address the problems described here:

- https://github.com/gumyr/build123d/issues/440
- https://github.com/gumyr/build123d/issues/441

and will close this issue.  Thanks for your dedication to making build123d better.
