### ISSUE TITLE
Regression: Lofts no longer work with Compound faces or ShapeList

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#438]
The input typing logic breaks when one of the `sections` is a `Compound`.

```py
p = Box(10,10,10)
f0 = (p.faces()>>Z)[0] + Pos(0,0,5)*Circle(6)
f1 = Pos(0,0,10) * Circle(5)
p += loft([f0, f1])
```
```
UnboundLocalError: cannot access local variable 'loft_wires' where it is not associated with a value
```

Workaround:
```py
p += loft([f0.face(), f1])
```

`loft([ShapeList])` has also stopped working (e.g. `loft([p.faces()>>Z, ...])`)

**Comment by jdegenstein** [comment]
This should be fixed by https://github.com/gumyr/build123d/pull/443 might be worthwhile to add a test to cover this case, but I did not do that yet.
