### ISSUE TITLE
Split should return both halves by default

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#454]
By namesake, split would be expected to split the object into two. The current operation, rather, by default splits the object in two and deletes half. A cleaner solution might be to remove the keep parameter all together:

```py
class SplitCompound(Compound):
  @property
  def split_halves() -> Tuple[Compound, Compound]: ...
  @property
  def top() -> Compound: ...
  ...

def split(...) -> SplitCompound:
  ...

split(part).top
```

**Comment by Jojain** [comment]
I don't agree, most use case of this you'll want to keep only one side of the split

**Comment by gumyr** [comment]
As @Jojain says, the most common use case is to keep only one side which is the default behavior. The docs describe the value of the `Keep` Enum as follows:
![image](https://github.com/gumyr/build123d/assets/85638518/bc2b680f-4553-4a62-8e3a-cc98fb1f1745)
which I think is quite clear.

Won't be changing this.
