### ISSUE TITLE
Fix Builder’s Pending Objects in the docs

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#467]
The example in the docs here: https://build123d.readthedocs.io/en/latest/key_concepts.html#builder-s-pending-objects is obsolete and needs to be updated.

**Comment by jdegenstein** [comment]
https://github.com/gumyr/build123d/commit/ceb898650788a8ab6a0e442847fd5868ef0305b3

updated to make the example complete and also change the names to the correct methods.
