### ISSUE TITLE
Adding an unrelated solid will undo a split

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#468]
The same issue occurs when using the Builder API.
```py
p = split(Box(1,1,1), keep=Keep.BOTH)
```
<img width="369" alt="Screenshot 1" src="https://github.com/gumyr/build123d/assets/149267773/dc4b5794-c433-43a7-80f9-a437dc3db1f5">

```py
p = split(Box(1,1,1), keep=Keep.BOTH)
p += Pos(0,2)*Sphere(0.5)
```
<img width="425" alt="Screenshot 2" src="https://github.com/gumyr/build123d/assets/149267773/2bbaf54b-e7c1-4c71-93c5-2383528b12dc">

**Comment by gumyr** [comment]
`BuildPart` is primarily intended to build a part so `Keep.BOTH` limited usefulness - although the split `Compound` object is returned so the user could save this result.  The `clean` operation is being applied when a new object is added to the part under construction which causes the previously `split` halves to merge together again.  If both halves are important, the `split` operation should be limited to the end of the `BuildPart` scope.

**Comment by MatthiasJ1** [comment]
The same issue is observed even when all operations are called with `clean=False`
