### ISSUE TITLE
pack leaves floating objects

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#469]
The `pack`'s docstring states `Pack objects in a squarish area in Plane.XY.`
I believe the intended use for this function is to arrange objects to be sent for cutting or 3d printing. In both cases you would want the objects placed on the plane.

BTW, theres no mention of `pack` in the documentation.

```py
parts = [Box(1,1,1)] * 6
parts[0] = Pos(0,0,2) * parts[0]
parts = pack(parts, 0.5)
```
<img width="257" alt="Screenshot" src="https://github.com/gumyr/build123d/assets/149267773/d0b28881-287d-4b1c-b593-f212a67f5479">

**Comment by jdegenstein** [comment]
Pack is mentioned on this page https://build123d.readthedocs.io/en/latest/tips.html

**Comment by MatthiasJ1** [comment]
Huh, the only thing that shows up when using the search bar is TTT Party Pack

**Comment by gumyr** [comment]
Even though `pack.pack()` is in the docs in the above section the RTD search engine doesn't find "pack".  The documentation of this feature could certainly be improved.

**Comment by erooke** [comment]
`align_z` was added in 9f189b0 which allows for this behavior. Should this be closed?
