### ISSUE TITLE
Intro Examples - STL export note

### ISSUE THREAD

**Issue by jdegenstein** [gumyr/build123d#513]
Improve the note near the top about exporting STL files to provide the alternative syntax for the algebra API.

**Comment by CePeU** [comment]
NewBox=Box1.part+Box2.part you get a new (part) Object which you can export with NewBox.export_stl while an object directly out of the builder needs to be exported by using NewBuilderBox.part.export_stl while on the other hand this distinction is totally irrelevant when using show_object

**Comment by Jojain** [comment]
If you are referring to OCP vscode show functions note that it is unrelated. OCP vscode is a separate project and can handle things it's in own way without b3d having anything to say about it.

It may be useful to state more strongly that builders are factory to build an object and the algebra api works directly on the object but once you understand that it's pretty obvious what builders do.

Maybe exemple could be modified to rename the builder instance with a proper name something like :
`with BuildPart() as part_builder:`
Then accessing the `part` attribute feels more natural

**Comment by gumyr** [comment]
See Issue #514 for some info on new error messages.

**Comment by jdegenstein** [comment]
This was fixed a while ago, closing issue
