### ISSUE TITLE
Circle SVG imported as multiple ellipses

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#520]
```py
circle_svg = StringIO("""
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <circle cx="50" cy="50" r="50" />
</svg>
""")

circle = import_svg(circle_svg)
v = circle.vertices()
print(circle.edges()[0].geom_type())
```
```
circle.edges()[0].geom_type() = 'ELLIPSE'
```
<img width="144" alt="Screenshot" src="https://github.com/gumyr/build123d/assets/149267773/268800b1-d4e2-40df-b829-ce807d20b094">

**Comment by gumyr** [comment]
build123d uses the svg importer from here: https://github.com/snoyer/ocpsvg.  Try raising the issue there.

**Comment by snoyer** [comment]
The underlying issue has been handled in `ocpsvg` and it looks like it fixed this issue in `build123d`
```py
print([e.geom_type for e in import_svg(StringIO('<svg><circle r="1"/></svg>')).edges()])
```
```
[<GeomType.CIRCLE>]
```
maybe @MatthiasJ1 can confirm and close if applicable

**Comment by gumyr** [comment]
I get `GeomType.CIRCLE` with ocpsvg 0.2.1. Closing the issue.  Thanks @snoyer!
