### ISSUE TITLE
split does not work with Sketches or Lines

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#525]
```py
p = split(SlotCenterToCenter(2, 4, 90).wire())
```
gives
```
IndexError: list index out of range
```
expected
<img width="289" alt="Screenshot" src="https://github.com/gumyr/build123d/assets/149267773/bac3237e-0bd0-4751-a96b-cf3e559031a0">

**Comment by gumyr** [comment]
With the latest I get the following:
![image](https://github.com/gumyr/build123d/assets/85638518/783b44b4-06e0-46ec-b856-1cfb68804f87)

Do you still see the error?

**Comment by MatthiasJ1** [comment]
Odd, I'm pretty sure this wasn't working when I opened the issue but it works now.
