### ISSUE TITLE
Call __str__ on Text txt parameter

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#538]
```py
Text(3, 10)
```
```
TypeError: __init__(): incompatible constructor arguments
```

**Comment by gumyr** [comment]
It's up to the user to pass the correct type arguments.  It isn't worth the effort to attempt to fix the user's mistakes throughout the whole API.

**Comment by MatthiasJ1** [comment]
Of course not, but Python has a language-wide builtin concept of stringification.
