### ISSUE TITLE
Add Sweep to BuildSketch for creating a planar face

### ISSUE THREAD

**Issue by jdegenstein** [gumyr/build123d#55]
Intended as a suggested enhancement to add Sweep to BuildSketch for creating a planar face. "sweep a 1/2D shape along a planar path to create a 2D shape"

This would need to check that the BuildLine segments are all coplanar, and also check that the resulting face has non-zero area.

**Comment by jdegenstein** [comment]
Has this feature been added? I would like to close this issue with some sample code.

**Comment by gumyr** [comment]
Not yet, it's just in the direct api at this point.

**Comment by gumyr** [comment]
Complete with c858b10e8b31573b377210043b38de2dbb229090
