### ISSUE TITLE
offset() function does not keep face normal

### ISSUE THREAD

**Issue by Windfisch** [gumyr/build123d#564]
Calling `offset(some_face, amount = -3)` does not keep the face normal. Apparently, it always rotates the face normal to point towards +X, +Y or +Z direction.

This is a problem if you depend on the normal of a face, e.g. for subsequent `extrude` operations.

## Reproducer

```py
from build123d import *
from ocp_vscode import *

box = Box(10,10,10)

offsets = [offset(face, amount=-3) for face in box.faces()]

show(offsets)
```

## Expected behavior
![offsetbug-expected](https://github.com/gumyr/build123d/assets/4471484/b78895b5-603c-4457-9f73-68635e5922ba)

(faces that are facing towards the camera are rendered in pink, faces that are facing away from the camera are gray)

## Actual behavior
![offsetbug](https://github.com/gumyr/build123d/assets/4471484/dc209c28-0cde-49b8-a858-3a0ae9706274)

**Comment by gumyr** [comment]
`offset` is working with Wires and I guess in some circumstances the direction of the perimeter after an offset is reversed resulting in the Face normal being flipped (the winding order of the outer wire determines the normal).  It shouldn't be too difficult to check for the reversal and if so, use `reverse` to flip the direction of the Wire before building the new Face.

**Comment by gumyr** [comment]
Fixed:
```py
box = Box(10, 10, 10)
original_faces = box.faces()
offset_faces = [offset(face, amount=-3).face() for face in original_faces]

for original_face, offset_face in zip(original_faces, offset_faces):
    assert original_face.normal_at() == offset_face.normal_at()
```
passes
![image](https://github.com/gumyr/build123d/assets/85638518/7c40d922-72f9-4162-858c-52cea11eac4e)
