### ISSUE TITLE
Swapped width and height in `Face.make_rect`

### ISSUE THREAD

**Issue by cyberhuman** [gumyr/build123d#565]
I noticed when trying to use `Face.make_rect` that it creates a rotated rectangle.
I checked the source code and calls OCC's `BRepBuilderAPI_MakeFace` with halfheight first, then halfwidth:
https://github.com/gumyr/build123d/blob/692de83ce238627b66f6a100529b298c6b348758/src/build123d/topology.py#L5409
But the arguments must be UMin, UMax, VMin, VMax. So it must be halfwidth first, then halfheight.

**Comment by gumyr** [comment]
Fixed with d1877e0debd612d896cf04a397810caac441fa10  Thanks for raising the Issue.
