### ISSUE TITLE
Add minor_radius as property of RegularPolygon

### ISSUE THREAD

**Issue by jdegenstein** [gumyr/build123d#585]
RegularPolygon currently has a radius property, but it would be nice to add a minor_radius property as well.

**Comment by gumyr** [comment]
What would a `minor_radius` do?

**Comment by gumyr** [comment]
Added the `apothem` attribute - which is the same term used in `HexLocations`. 
![image](https://github.com/gumyr/build123d/assets/85638518/f7b93346-7b85-4727-820c-654fd568a679)
