### ISSUE TITLE
Option to highlight edge/vertex/face

### ISSUE THREAD

**Issue by proegssilb** [gumyr/build123d#592]
I find myself writing a lot of `filter_by_position()` selectors. It'd be nice to be able to highlight the results of a selector for debugging purposes, not unlike `#` in OpenSCAD. For example, `to_fillet = part.edges().filter_by_position(Axis.Z, 41, 43).debug()` or `to_fillet = part.edges().filter_by_position(Axis.Z, 41, 43).highlight()`

**Comment by gumyr** [comment]
`show(to_fillet)` (with ocp_vscode) or `show_object(to_fillet)` (both cq-editor and ocp_vscode)

The build123d API is not tied to any viewer so one needs to execute viewer specific commands to display objects.
