### ISSUE TITLE
Add better repr to Color class

### ISSUE THREAD

**Issue by jdegenstein** [gumyr/build123d#596]
```py
print(Color(*(.3,.5,.6)))
```
Returns: `Color: (0.30000001192092896, 0.5, 0.6000000238418579, 1.0)`
```py
Color(*(.3,.5,.6))
```
Returns: `<build123d.geometry.Color at 0x12f6e8eb3d0>`

**Comment by gumyr** [comment]
After 6eb00f1ef94fa4d5eb2b94c7ff6c39c0839b80f7:
```py
>>> str(Color(*(.3,.5,.6)))
'Color: (0.30000001192092896, 0.5, 0.6000000238418579, 1.0) ~ LIGHTBLUE3'
>>> Color(*(.3,.5,.6))
Color(0.30000001192092896, 0.5, 0.6000000238418579, 1.0)
```

**Comment by jdegenstein** [comment]
Wow that was fast, thanks!

**Comment by gumyr** [comment]
The string now returns the closest named color which is a good sanity check that the color is correct.
