### ISSUE TITLE
`Locations` provided outside of the scope of a Builder are ignored

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#61]
These two tests should provide the same results:
```py
with BuildPart() as test1:
    Box(10, 10, 10)
    with BuildSketch(*test1.faces()):
        with GridLocations(5, 5, 2, 2):
            Circle(1)
    Extrude(amount=1)

with BuildPart() as test2:
    Box(10, 10, 10)
    with GridLocations(5, 5, 2, 2):
        with BuildSketch(*test2.faces()):
            Circle(1)
    Extrude(amount=1)
```
but they don't (Blue is test1):
![image](https://user-images.githubusercontent.com/85638518/204844169-b01c7218-214f-413b-9ad4-14e0b771de31.png)

**Comment by gumyr** [comment]
@bernhard-42 provided a more mathematically correct answer - there should be four sets of six cylinders as location multiplication is not cumulative.  This implies that Workplanes should follow existing Locations.

**Comment by gumyr** [comment]
![image](https://user-images.githubusercontent.com/85638518/205077556-8a578708-4ff7-491f-92ff-9e59c8f3b0cb.png)

**Comment by jmcmullan** [comment]
This bug is no longer present, now that #94 has been closed.

Both 'test1' and 'test2' generate identical parts.

**Comment by gumyr** [comment]
Thanks @jmcmullan, you're right they generate the same parts now with the nesting fix.  What about the "not cumulative" discussion above - does it make sense that they generate the same part?

**Comment by jmcmullan** [comment]
I would expect that they generate the same part, in that the 'origin' of a BuildSketch() under a 'with Locations()' would be centered at the location in question.

**Comment by gumyr** [comment]
I agree with you @jmcmullan. Although the more complex interpretation may ultimately be the correct one, I'm going to close this issues as I believe this is the behaviour that would be expected by most users.  Thanks for the help!

**Comment by AlexVerschoot** [comment]
In version 0.10.1.dev356+g44e8e4566 this bug is present again:
```
    with BuildPart() as test1:
        Box(10, 10, 10)
        with BuildSketch(*test1.faces()):
            with GridLocations(5, 5, 2, 2):
                Circle(1)
        extrude(amount=1)

    with BuildPart() as test2:
        Box(10, 10, 10)
        with GridLocations(5, 5, 2, 2):
            with BuildSketch(*test2.faces()):
                Circle(1)
        extrude(amount=1)
```
