### ISSUE TITLE
Thicken normal incorrect

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#623]
```py
l1 = JernArc((0,0), (-1,0), 1, 180).edge().reversed()
l2 = JernArc((0,0), (1,0), 2, -90)
s = RadiusArc((0,0), (0,-1), 1)
f = sweep((l1^0)*s, l1) + sweep((l2^0)*s, l2) # Workaround for #622
```
<img width="397" alt="1" src="https://github.com/gumyr/build123d/assets/149267773/b0d92093-cb3f-4a47-99a2-e54de0fe9993">

```py
p = thicken(f, 0.4)
```
<img width="397" alt="2" src="https://github.com/gumyr/build123d/assets/149267773/45431c47-9a40-4094-9156-35db24c7ad41">

**Comment by gumyr** [comment]
There is a `normal_override` parameter of thicken to help cope with these situations:
```py
p = thicken(f, 0.4, normal_override=(0, 1, 0))
```
![image](https://github.com/gumyr/build123d/assets/85638518/0a05ad4c-f31e-4de3-ab54-86a17aa0b9a7)

When `thicken` was developed controlling the normal was found to be difficult so this override was added as the best solution at the time.

**Comment by MatthiasJ1** [comment]
Shouldn't it just thicken in the face normal?
