### ISSUE TITLE
Add major_radius bool to HexLocations

### ISSUE THREAD

**Issue by jdegenstein** [gumyr/build123d#633]
Currently `RegularPolygon` supports bool `major_radius` that defaults to `True`. In order to place hexagonal regular polygons with sides touching with the default option, one must use math to convert the major radius to minor radius (aka the apothem). I propose adding `HexLocations(... major_radius: bool = False)` which will preserve the existing default behavior, while allowing for better interoperability between `RegularPolygon` and `HexLocations`.

```py
with BuildSketch() as s:
    with HexLocations(1,3,3):
        RegularPolygon(1,6)
```
![image](https://github.com/gumyr/build123d/assets/16868537/d567ac27-25c9-4a3e-9453-852ed7a75d79)

**Comment by gumyr** [comment]
If one does this:
```py
with BuildSketch() as s:
    with HexLocations(1, 3, 3):
        RegularPolygon(1, 6, major_radius=False)
```
the hexes touch each other.  Is the problem that you want to work with a major radius for both `HexLocations` and `RegularPolygon`?

**Comment by jdegenstein** [comment]
Yes, that is the use-case that I would like to make a bit easier.
