### ISSUE TITLE
doc: Mention `show(example)` at the very beginning of the tutorial

### ISSUE THREAD

**Issue by blinry** [gumyr/build123d#669]
Hey :) We tried following the [Selectors tutorial](https://build123d.readthedocs.io/en/latest/tutorial_selectors.html). When we tried running the code after step 2, we were surprised that we didn't get any output.

For very new users like ourselves, it would be good to mention `show(example)` at the very beginning, before step 6, so you can run the steps individually, and see your progress.

**Comment by gumyr** [comment]
Done.  Thanks for pointing this out.
