### ISSUE TITLE
PositionMode.LENGTH incorrect

### ISSUE THREAD

**Issue by MatthiasJ1** [gumyr/build123d#670]
```py
w = Wire([Line(v1, v2).edge() for v1,v2 in itertools.pairwise([Vector(a,0) for a in [(i/10)**2 for i in range(0, 11)]])]).close()
s = w.positions(range(11), PositionMode.LENGTH)
```

![Screenshot](https://github.com/user-attachments/assets/60f94d40-6341-443d-82ea-eda5fb492a81)

- These should be uniformly spaced
- The overall length of this Wire is 1, yet it fits sample points at distances of up to 10

**Comment by jdegenstein** [comment]
Are you sure this is working right? I am having similar problems. I think the issue is :
```py
class Mixin1D:
...
        law.D0(param, tangent, normal, binormal)
        pnt = curve.Value(param)
```
It is not clear to me what the law is actually doing here, and I am having some trouble getting results that I expect.
