### ISSUE TITLE
Step import fails to position parts correctly.

### ISSUE THREAD

**Issue by gumyr** [gumyr/build123d#671]
The step file: https://github.com/tpaviot/pythonocc-demos/blob/master/assets/models/as1-oc-214.stp appears as:
![image](https://github.com/user-attachments/assets/2faf60a3-81cb-4010-b650-af81eceb51a7)
in FreeCAD but
![image](https://github.com/user-attachments/assets/5ad2a8fd-f271-441f-92b5-75c203fa792d)
in build123d.

There are two `l-bracket-assembly` objects but they are in the same location.

**Comment by jdegenstein** [comment]
![image](https://github.com/user-attachments/assets/a52ad390-9977-41e0-be7b-fa06b4c58630)

Here is a screenshot of the topology tree in Mayo which properly imports the file

**Comment by gumyr** [comment]
A big thanks to @bernhard-42 for an alternate implementation and @jdegenstein for helping to debug the issue. It should be fixed now.
