### ISSUE TITLE
Pack demo assets not showing in docs

### ISSUE THREAD

**Issue by jdegenstein** [gumyr/build123d#689]
on this page some of the links are broken to the SVG files https://build123d.readthedocs.io/en/latest/assemblies.html#pack

**Comment by jdegenstein** [comment]
@roman-dvorak can you add the missing SVG files for the pack function? https://github.com/gumyr/build123d/pull/641

**Comment by roman-dvorak** [comment]
I apologize for the delay. Images are attached in the new PR. Thanks for pinging me again.

**Comment by jdegenstein** [comment]
Closed by https://github.com/gumyr/build123d/commit/1c653f87b939e61ef6b72adef98d582f58dbcef3 thanks again!
