### ISSUE TITLE
2D Offset breaks due to overlapping wires

### ISSUE THREAD

**Issue by CarpeNecopinum** [gumyr/build123d#702]
Minimal reproducing example:
```py
from build123d import *

sk = Rectangle(100, 100) - GridLocations(80, 80, 2, 2) * Circle(5)
part = extrude(sk, 10)

sk2 = offset((part.faces() >> Axis.Z).first, -5)
part -= extrude(sk2, -5)
```
creates the following (broken) part:

![image](https://github.com/user-attachments/assets/93cd27a0-940b-4a2a-8dc8-414a3c10731b)

Replacing the `offset` function with the following `safe_offset2D` function
```py
def safe_offset2d(face: Face, offset: float):
    outer = face.outer_wire().offset_2d(offset)
    inners = [inner.offset_2d(-offset) for inner in face.inner_wires()]
    new_face = Face(outer)
    for inner in inners:
        new_face -= Face(inner)
    return new_face
```

yields the desired result:

![image](https://github.com/user-attachments/assets/963a2d4d-033a-4b81-8889-0df12eec5ec7)

The culprit is likely to be https://github.com/gumyr/build123d/blob/dev/src/build123d/operations_generic.py#L619 where a new Face is created from the offset outer and inner wires, without checking for potential overlap between them.

**Comment by gumyr** [comment]
Fixed:
```py
sk = Rectangle(100, 100) - GridLocations(80, 80, 2, 2) * Circle(5)
sk2 = sk - offset(sk, -5)
```
![image](https://github.com/user-attachments/assets/1109f3c4-aff5-4877-ac62-85bba07bfe59)
