### ISSUE TITLE
Typo(?) in general_examples_algebra.py, example 23.

### ISSUE THREAD

**Issue by javimixet** [gumyr/build123d#714]
I had to change code in line 389 from `sk23 = make_face(l1, l2)` to `sk23 = make_face(l1 + l2)` for the revolve to work.

**Comment by jdegenstein** [comment]
Thanks for reporting! I added to my PR here https://github.com/gumyr/build123d/pull/715, but I used a slightly different solution: `sk23 = make_face([l1, l2])` which I think was probably what was originally intended.
