### ISSUE TITLE
Test enforces stricter version bounds than pyproject.toml

### ISSUE THREAD

**Issue by erooke** [gumyr/build123d#731]
The test `test_version` fails if `py_lib3mf` is anything *but* version 2.3.1.

https://github.com/gumyr/build123d/blob/8e798f2b577f58b4ea372fa3f67ba53d566ff2c8/tests/test_mesher.py#L37-L39

however the `pyproject.toml` asserts that `py_lib3mf` must be at least version 2.3.1.

https://github.com/gumyr/build123d/blob/8e798f2b577f58b4ea372fa3f67ba53d566ff2c8/pyproject.toml#L45

**Comment by jdegenstein** [comment]
Thanks for reporting, the test needs to be improved to use the proper version comparison method from `from packaging.version import Version`
