### ISSUE TITLE
`cut` returns objects with dimension not set

### ISSUE THREAD

**Issue by smurfix** [gumyr/build123d#736]
`cut` returns an object with dimension not set. As build123d has a couple of tests that verify matching dimensions on its operations., its result is somewhat unuseable.

```
>>> res
Box at 0x7f5b8084f010, label(), #children(0)
>>> c
Box at 0x7f5b819a7a50, label(), #children(0)
>>> res.cut(c)._dim
None
>>> (res-c)._dim
3
>>> res.cut(c)-c
*** TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

**Comment by gumyr** [comment]
`cut` is returning a `Compound` object which could be of any dimension which is why `_dim` is not set.  This is an aspect of the OCCT CAD kernel and can't be changed.

**Comment by gumyr** [comment]
Commit 0b4b2b2b54422561e9c7b8b0d2e97cde7a16bbea "solves" this issue by providing a new `_dim` property to all objects such that a `Compound` object inherits the dimension of the objects within it if all of those objects are the same dimension. Otherwise a value of None is returned.
