### ISSUE TITLE
What are the correct parameters for `sweep`

### ISSUE THREAD

**Issue by RFARREY** [gumyr/build123d#748]
It seems there's a discrepancy between the Build123d documentation and the actual implementation in version 0.7.0.

The sweep function in this version doesn't accept the section parameter, and it seems the documentation is outdated.

**Comment by jdegenstein** [comment]
There are currently 4 different functions or methods named `sweep` in build123d. They do not have the same parameters, 3 of these are "direct API" methods which is the lowest level API of build123d. The `sweep` function itself accepts a parameter `sections` and `Solid.sweep` accepts a parameter `section` (singular).
```py
sweep()
Face.sweep()
Shell.sweep()
Solid.sweep()
```
https://build123d.readthedocs.io/en/latest/search.html?q=sweep&check_keywords=yes&area=default#

**Comment by jdegenstein** [comment]
@RFARREY did the above address your question / concern?

**Comment by KilowattSynthesis** [comment]
Whether it answers the question, there's a few of these where methods with the same name have different arguments, different argument orderings, and different semantics. It's really too bad.

**Comment by jdegenstein** [comment]
@KilowattSynthesis PRs/issues are welcome to fix any inconsistencies you may find. In this case `section` vs. `sections` is an intentional difference between the two.

I am closing this issue as we have not received any response in several weeks from the author.

**Comment by KilowattSynthesis** [comment]
Fair enough; I think I was misunderstanding the difference. Cheers!
