### ISSUE TITLE
new feature if it is possibile

### ISSUE THREAD

**Issue by AhmedOmarYounusShahhat** [gumyr/build123d#789]
i am using this library since couple of months and it is really great library !! i am just wondering if there is anyway that my cad files could be converted to a code in automatic way in build or algebra mode ? that will be amazing feature if it is possible or if there is any work around to make it possible and thanks !!! great job guys

**Comment by gumyr** [comment]
The only thing even close to this is `import_svg_as_buildline_code` which is a modest attempt to convert the lines of an SVG file into `BuildLine` code which can be further edited.  One possibility that really in its infancy is having AI systems to do this conversion - see the [External Tools and Libraries](https://build123d.readthedocs.io/en/latest/external.html#tools) section of the docs for links to some of these projects.
