### ISSUE TITLE
Rotation for workplanes

### ISSUE THREAD

**Issue by fpq473** [gumyr/build123d#8]
```py
import build123d as bd

with bd.BuildPart() as bp:
    bd.Box(3,3,3)
    bd.WorkplanesFromFaces(*bp.faces())
    bd.Box(1,2,0.1,rotation=(0,0,45))
```

Currently gives the first solid, but was expecting the second.

![image](https://user-images.githubusercontent.com/103151053/189948378-e897b3a9-8d72-4b6e-8787-b04474719931.png)

**Comment by gumyr** [comment]
This is the new syntax, and the result:
```py
import build123d as bd

with bd.BuildPart() as bp:
    bd.Box(3, 3, 3)
    with bd.Workplanes(*bp.faces()):
        bd.Box(1, 2, 0.1, rotation=(0, 0, 45))

if "show_object" in locals():
    show_object(bp.part, name="box on faces")
```
![Screenshot from 2022-09-14 13-12-07](https://user-images.githubusercontent.com/85638518/190495397-58748619-41d2-4ee0-8729-da99b6a8ac89.png)

This issue was fixed with 69abdd9c450441028cc9b71f0dfe75d6d23a00c5
