### ISSUE TITLE
Feature Request: Add `.translate(x=..., y=..., z=...)` kwarg overloads

### ISSUE THREAD

**Issue by KilowattSynthesis** [gumyr/build123d#803]
Currently, the only way to use `.translate(...)` is by supplying a tuple/vector. If you only want to translate on a single axis, you must provide a tuple (or similar) with two 0 elements.

It would be awesome to be able to call `.translate(y=12)` to move on just one axis.

This would be especially helpful to avoid deeper indentation when using an autoformatter, for example when one argument is very long and the rest are zero.

**Comment by gumyr** [comment]
`translate` doesn't just move the object (i.e. change the object's location) but actually recreates the object in the new position which is quite an expensive operation.  Users should generally use the mechanisms to re-locate an object: `move`, `moved`, `locate`, `located`, `obj.position = (...)`, `obj.position += (...)` or the Algebra`*` operator.

The `Pos` class returns a `Location` and supports a keyword interface (`X`, `Y`, `Z`) so `obj.move(Pos(X=#))` or `Pos(X=#) * obj` does what you'd like to do in a more efficient way than `translate`. Here is an example:
```py
from build123d import *
from ocp_vscode import show_all

b = Box(1, 1, 1)
b.color = Color("Blue")
scaled = Pos(X=1.5) * scale(b, (1, 1, 0.5))

show_all()
```
`translate`may be eliminated from the API or re-implemented as a move in the future.

**Comment by KilowattSynthesis** [comment]
I way prefer method chaining compared to the mulitplication operation. I maintain my point.

The internal implementation of a move vs. a translate has nothing to do with this feature request

**Comment by gumyr** [comment]
Method chaining is not the preferred design pattern of build123d. There is no guarantee that the direct api and the operations are exactly the same.
