### ISSUE TITLE
Feature Request: Add automatic part packing

### ISSUE THREAD

**Issue by KilowattSynthesis** [gumyr/build123d#815]
It would be great if there was a function which automatically packaged several parts onto a "print bed" of sorts, like how 3d printer slicer programs do.

**Comment by gumyr** [comment]
https://build123d.readthedocs.io/en/latest/assemblies.html#id1

**Comment by KilowattSynthesis** [comment]
It's really too bad the readthedocs search is sorta useless on the description part. Feeling pretty dumb for glancing over it on this search, but also, it doesn't pop out as related to part packing at all:

![image](https://github.com/user-attachments/assets/8b977b79-a5a1-49e4-8c56-c61adb50a67e)

Probably nothing you can do about that though
