### ISSUE TITLE
Placed Sketch instead of Un-Placed Sketch

### ISSUE THREAD

**Issue by jdegenstein** [gumyr/build123d#88]
When calling `show_object(mains.sketch)`, the resulting sketch is the "unplaced" version located at the default Plane.XY. This is confusing to users, and it was suggested that `sketch -> _sketch` and to create a new `sketch` property which is the placed version of `_sketch`.
```py
from build123d import *

with BuildPart() as mainp:
    with BuildSketch(Plane(origin=(10,10)),
                     Plane(origin=(10,-10))) as mains:
        Rectangle(2,5,centered=(False,False))
        Circle(2)
    Extrude(amount=1)

show_object(mains.sketch,options=rand_color())
show_object(mainp.part,options=rand_color())
```
![image](https://user-images.githubusercontent.com/16868537/210397864-29ad9e5f-9627-4c9c-90b9-83b9a6ffa452.png)

**Comment by gumyr** [comment]
Fixed with commit https://github.com/gumyr/build123d/commit/de3ed2e66461741dc26a3ba348c97b1630e8c32e

The `sketch` property represents the global view of the sketch (two in this example), while `sketch_local` is equivalent to the previous `sketch` attribute.
